from __future__ import annotations

from .schema import SourceRecord


SEED_BENCHES = [
    {
        "name": "GDPval",
        "slug": "gdpval",
        "phase": "train",
        "status": "resolved",
        "aliases": ["GDP val", "GDPval gold"],
        "organization": "OpenAI",
        "year": "2025",
        "domain": ["real-world work", "economics", "professional services"],
        "evaluates": "Model performance on economically valuable real-world knowledge-work tasks across 44 occupations and 9 U.S. GDP-linked industries.",
        "task_format": "One-shot professional deliverables with reference files, such as documents, slides, diagrams, spreadsheets, care plans, briefs, and blueprints.",
        "task_categories": [
            "professional deliverable generation",
            "occupational knowledge work",
            "document and presentation creation",
            "spreadsheet and diagram production",
        ],
        "evaluation_method": "Expert blind comparison against human deliverables, with rubric support and an experimental automated grader.",
        "dataset_size": "1,320 full-set tasks; 220 open gold-set tasks.",
        "data_access": "Gold subset and grading service are public; full set is not fully public.",
        "artifacts": {
            "project": "https://openai.com/index/gdpval/",
            "eval_service": "https://evals.openai.com/",
        },
        "sources": [
            SourceRecord(
                "OpenAI GDPval announcement",
                "https://openai.com/index/gdpval/",
                "official",
                "Primary description of scope, occupations, task design, and grading.",
            )
        ],
        "reliability_notes": [
            "Good first training case for schema design because the official page is detailed and stable.",
            "Scores are partly shown through OpenAI figures/paper and may need deeper extraction later.",
        ],
        "paper_analysis": {
            "core_question": "Can frontier models produce real-world professional deliverables that experts prefer or judge competitive with human work?",
            "motivation": "Most standard benchmarks over-index on exam-style questions and short answers, while economically valuable work often requires producing artifacts such as briefs, slides, spreadsheets, plans, and blueprints.",
            "gap_claimed": "GDPval targets the gap between benchmark competence and real occupational output quality across GDP-linked industries.",
            "evaluated_capabilities": [
                "professional deliverable generation",
                "domain-specific reasoning",
                "instruction following over reference files",
                "artifact quality judged by experts",
            ],
            "benchmark_design": {
                "data_source": "Tasks are designed around 44 occupations across 9 U.S. GDP-linked industries.",
                "task_construction": "Each task asks the model to produce a realistic work deliverable rather than only a short answer.",
                "task_types": ["documents", "presentations", "spreadsheets", "diagrams", "care plans", "briefs", "blueprints"],
                "gold_generation": "Human expert deliverables serve as comparison targets for blind evaluation.",
                "world_or_case_design": "Work is framed as real occupational tasks with associated reference files and expected professional artifacts.",
                "tools_or_environment": ["reference files", "document generation", "spreadsheet generation", "presentation generation"],
                "expert_involvement": "Domain experts are used for blind comparison and grading.",
            },
            "rubric_and_scoring": {
                "gold_definition": "Gold is represented by human expert work products and expert preference/quality judgments.",
                "rubric_dimensions": ["quality of deliverable", "task satisfaction", "professional usefulness"],
                "metrics": ["expert preference", "win rate", "rubric-supported score"],
                "scoring_protocol": "Experts compare model outputs with human deliverables under blind review; an automated grader is experimental.",
                "judge_type": "human expert plus automated grader research path",
                "human_review": "Yes, expert blind comparison is central.",
            },
            "model_results_summary": "The benchmark is intended to compare frontier models against human deliverables, with emphasis on whether expert reviewers prefer or accept model outputs.",
            "main_findings": [
                "Frontier models can produce useful professional artifacts in some occupations.",
                "Performance varies by occupation and deliverable type.",
                "The benchmark reveals gaps that are not visible in short-answer tests.",
            ],
            "conclusions": [
                "Economic-work benchmarks need expert judgment and realistic deliverables.",
                "Model progress should be assessed on task usefulness, not only answer correctness.",
            ],
            "failure_modes": [
                "Outputs may look plausible but miss professional details.",
                "Models can struggle with long artifacts, formatting constraints, and domain-specific expectations.",
                "Automated grading may not fully capture expert quality judgments.",
            ],
            "reliability_notes": [
                "Full task set is not fully public, so reproducibility depends on released gold subset and grading service.",
                "Expert evaluation is valuable but expensive and may be harder to replicate independently.",
            ],
        },
        "confidence": 0.95,
    },
    {
        "name": "SpreadsheetBench v2",
        "slug": "spreadsheetbench-v2",
        "phase": "train",
        "status": "resolved",
        "aliases": ["SpreadsheetBench 2", "Spreadsheet Bench v2"],
        "organization": "SpreadsheetBench authors",
        "year": "2026",
        "domain": ["spreadsheet", "business workflow", "finance"],
        "evaluates": "Agents on end-to-end business spreadsheet workflows rather than isolated cell edits or single formulas.",
        "task_format": "Multi-turn spreadsheet tasks over multi-sheet workbooks; agents must generate, debug, or visualize spreadsheet deliverables.",
        "task_categories": ["generation", "debugging", "visualization"],
        "evaluation_method": "Task-level accuracy under a unified agent scaffold, with workflow outputs checked against expected spreadsheet outcomes.",
        "dataset_size": "321 tasks; reported average of 11.8 worksheets and 593.5 cell modifications per task.",
        "data_access": "Public project, GitHub, and Hugging Face dataset are available.",
        "artifacts": {
            "project": "https://spreadsheetbench.github.io/",
            "paper": "https://arxiv.org/abs/2606.29955",
            "github": "https://github.com/RUCKBReasoning/SpreadsheetBench-2",
            "dataset": "https://huggingface.co/datasets/KAKA22/SpreadsheetBench-v2",
        },
        "sources": [
            SourceRecord(
                "SpreadsheetBench project page",
                "https://spreadsheetbench.github.io/",
                "project",
                "Primary project page for SpreadsheetBench and SpreadsheetBench 2.",
            ),
            SourceRecord(
                "SpreadsheetBench 2 paper",
                "https://arxiv.org/abs/2606.29955",
                "paper",
                "Paper abstract gives task count, task categories, and reported benchmark framing.",
            ),
        ],
        "reliability_notes": [
            "Good training case for workflow and spreadsheet-specific capability tags.",
            "Leaderboard/model scores should be extracted from paper tables in a later iteration.",
        ],
        "paper_analysis": {
            "core_question": "Can agents complete end-to-end business spreadsheet workflows rather than isolated spreadsheet edits?",
            "motivation": "Earlier spreadsheet benchmarks often focus on single-step formula/cell operations, which underrepresent real business spreadsheet work.",
            "gap_claimed": "SpreadsheetBench v2 claims to move from atomic spreadsheet operations to full workflow tasks involving generation, debugging, and visualization.",
            "evaluated_capabilities": [
                "spreadsheet workflow execution",
                "multi-sheet reasoning",
                "formula and cell modification",
                "debugging",
                "chart or visualization generation",
                "long-horizon agent operation",
            ],
            "benchmark_design": {
                "data_source": "Business spreadsheet tasks packaged as workbooks with multiple worksheets.",
                "task_construction": "Tasks require agents to modify or create workbook content across many cells and sheets.",
                "task_types": ["generation", "debugging", "visualization"],
                "gold_generation": "Expected workbook outcomes and task-specific checks define the target behavior.",
                "world_or_case_design": "Tasks model business spreadsheet workflows rather than standalone question answering.",
                "tools_or_environment": ["spreadsheet files", "multi-sheet workbooks", "agent scaffold"],
                "expert_involvement": "Needs deeper paper extraction; seed profile only confirms benchmark authors designed workflow tasks.",
            },
            "rubric_and_scoring": {
                "gold_definition": "Gold is the expected spreadsheet state or task-specific output after completing the workflow.",
                "rubric_dimensions": ["task completion", "cell modification correctness", "workflow output correctness"],
                "metrics": ["Task Accuracy", "Modification Accuracy"],
                "scoring_protocol": "Agents are evaluated by comparing generated or modified spreadsheet outputs against expected outcomes.",
                "judge_type": "automatic/task-specific checks",
                "human_review": "Not central in the seed description; verify from paper.",
            },
            "model_results_summary": "The benchmark reports that current agents still struggle with realistic long spreadsheet workflows.",
            "main_findings": [
                "Spreadsheet workflows remain difficult even for strong agents.",
                "End-to-end workbook tasks expose failures hidden by single-step spreadsheet benchmarks.",
                "Debugging and visualization require different capabilities from formula completion.",
            ],
            "conclusions": [
                "Spreadsheet evaluation should measure full business workflow completion.",
                "Agents need better long-horizon planning, workbook state tracking, and tool reliability.",
            ],
            "failure_modes": [
                "Incorrect cell modifications across sheets.",
                "Loss of workbook context over long tasks.",
                "Formula/debugging mistakes.",
                "Visualization outputs that fail task-specific requirements.",
            ],
            "reliability_notes": [
                "Model results and scoring details should be verified from paper tables and code.",
                "Large spreadsheet artifacts require careful reproducibility checks.",
            ],
        },
        "confidence": 0.93,
    },
    {
        "name": "FAB",
        "slug": "fab",
        "phase": "train",
        "status": "resolved",
        "aliases": ["Finance Agent Benchmark", "Finance Agent v2", "FAB v2"],
        "organization": "Vals AI",
        "year": "2025/2026",
        "domain": ["finance", "financial analysis", "agent evaluation"],
        "evaluates": "LLM agents on realistic entry-level financial analyst tasks involving public company filings and financial research.",
        "task_format": "Question answering with an agentic harness and tools such as search and SEC/EDGAR filing access.",
        "task_categories": [
            "financial information retrieval",
            "SEC filing analysis",
            "financial modeling",
            "company research",
        ],
        "evaluation_method": "Accuracy-based benchmark with expert-reviewed questions; v2 uses a refreshed taxonomy and evaluation harness.",
        "dataset_size": "v1.1 paper reports 537 questions; FAB v2 page reports 927 expert-reviewed questions.",
        "data_access": "Public GitHub/Hugging Face resources exist for earlier versions; v2 leaderboard and splits are hosted by Vals AI.",
        "artifacts": {
            "leaderboard": "https://vals.ai/benchmarks/fabv2",
            "github": "https://github.com/vals-ai/finance-agent",
            "dataset": "https://huggingface.co/datasets/vals-ai/finance_agent_benchmark",
            "paper": "https://arxiv.org/abs/2508.00828",
        },
        "sources": [
            SourceRecord(
                "Finance Agent v2 leaderboard",
                "https://vals.ai/benchmarks/fabv2",
                "leaderboard",
                "Vals AI benchmark page for FAB v2.",
            ),
            SourceRecord(
                "Finance Agent Benchmark paper",
                "https://arxiv.org/abs/2508.00828",
                "paper",
                "Paper for Finance Agent Benchmark v1.1.",
            ),
        ],
        "reliability_notes": [
            "Name has acronym collision risk; aliases are important.",
            "v1.1 and v2 have different question counts, so reports should preserve version context.",
        ],
        "paper_analysis": {
            "core_question": "Can LLM agents perform realistic financial analyst research using public filings, search, and financial reasoning?",
            "motivation": "General QA or finance text benchmarks do not capture the tool-using research workflow of entry-level financial analysts.",
            "gap_claimed": "FAB targets the gap between static finance QA and agentic finance workflows over filings, search, and calculations.",
            "evaluated_capabilities": [
                "financial information retrieval",
                "SEC filing navigation",
                "company research",
                "financial reasoning",
                "tool use",
                "calculation grounded in source documents",
            ],
            "benchmark_design": {
                "data_source": "Questions are built around public company information, SEC/EDGAR filings, and financial research tasks.",
                "task_construction": "Agents answer finance questions using an evaluation harness with retrieval and filing-access tools.",
                "task_types": ["company research", "filing lookup", "financial calculation", "financial modeling"],
                "gold_generation": "Expert-reviewed answers define expected outputs; version-specific details differ between v1.1 and v2.",
                "world_or_case_design": "Tasks simulate junior financial analyst workflows rather than isolated textbook finance questions.",
                "tools_or_environment": ["web search", "SEC/EDGAR", "filing parser", "agent harness"],
                "expert_involvement": "FAB v2 describes expert-reviewed questions; v1.1 paper details should be extracted for precision.",
            },
            "rubric_and_scoring": {
                "gold_definition": "Gold answers are expert-reviewed finance answers tied to source documents or calculations.",
                "rubric_dimensions": ["answer correctness", "source-grounded retrieval", "calculation correctness"],
                "metrics": ["accuracy", "score"],
                "scoring_protocol": "Agent answers are compared to benchmark answers under the Vals evaluation harness.",
                "judge_type": "automatic benchmark grading with expert-reviewed items",
                "human_review": "Expert review is used in question/answer construction.",
            },
            "model_results_summary": "FAB is used as a leaderboard-style benchmark for comparing finance agents and frontier models under tool use.",
            "main_findings": [
                "Finance agents benefit from reliable retrieval and filing access.",
                "Strong language models can still fail when source lookup or calculation is brittle.",
                "Version differences matter because v1.1 and v2 have different question sets.",
            ],
            "conclusions": [
                "Financial analysis benchmarks need tool use and source-grounded reasoning.",
                "Leaderboard results should be interpreted with version and harness details preserved.",
            ],
            "failure_modes": [
                "Retrieving the wrong filing or wrong period.",
                "Incorrect financial calculation despite finding the right source.",
                "Overconfident answer without source verification.",
                "Confusing benchmark versions or metrics.",
            ],
            "reliability_notes": [
                "FAB acronym has collision risk; version resolution is required.",
                "v1.1 and v2 counts/results should not be merged without version labels.",
            ],
        },
        "confidence": 0.91,
    },
    {
        "name": "APEX",
        "slug": "apex",
        "phase": "test",
        "status": "resolved",
        "aliases": ["APEX-Agents", "AI Productivity Index", "APEX Benchmarks"],
        "organization": "Mercor",
        "year": "2026",
        "domain": ["professional services", "agent evaluation", "economic work"],
        "evaluates": "Frontier AI agents on economically valuable, long-horizon professional tasks.",
        "task_format": "Cross-application professional work environments with files and tools, including docs, spreadsheets, PDFs, email, chat, and calendar.",
        "task_categories": [
            "investment banking",
            "management consulting",
            "corporate law",
            "professional service deliverables",
        ],
        "evaluation_method": "Pass@1-style task success with rubrics and realistic work artifacts.",
        "dataset_size": "APEX-Agents paper reports 480 tasks; related leaderboard pages may expose subsets.",
        "data_access": "Public benchmark artifacts are reported for APEX-Agents.",
        "artifacts": {
            "project": "https://www.mercor.com/apex/",
            "leaderboard": "https://www.mercor.com/apex/apex-agents-leaderboard/",
            "paper": "https://arxiv.org/abs/2601.14242",
            "dataset": "https://huggingface.co/datasets/mercor/apex-agents",
        },
        "sources": [
            SourceRecord(
                "Mercor APEX benchmarks",
                "https://www.mercor.com/apex/",
                "official",
                "Family page for Mercor APEX benchmarks.",
            ),
            SourceRecord(
                "APEX-Agents paper",
                "https://arxiv.org/abs/2601.14242",
                "paper",
                "Paper abstract describes long-horizon professional-service agent tasks.",
            ),
        ],
        "reliability_notes": [
            "APEX is a family name; the pipeline resolves it toward APEX-Agents for now.",
            "Version and subset should be clarified when extracting scores.",
        ],
        "confidence": 0.86,
    },
    {
        "name": "FinSearchComp",
        "slug": "finsearchcomp",
        "phase": "test",
        "status": "resolved",
        "aliases": ["Fin Search Comp", "Financial Search Competition"],
        "organization": "FinSearchComp authors",
        "year": "2025",
        "domain": ["finance", "search", "reasoning"],
        "evaluates": "End-to-end agents on realistic open-domain financial search and reasoning.",
        "task_format": "Financial search questions requiring time-sensitive fetching, historical lookup, or multi-source investigation.",
        "task_categories": [
            "time-sensitive data fetching",
            "simple historical lookup",
            "complex historical investigation",
        ],
        "evaluation_method": "Answer accuracy over expert-annotated financial search tasks, including global and Greater China market coverage.",
        "dataset_size": "635 questions.",
        "data_access": "Project and GitHub indicate open benchmark resources.",
        "artifacts": {
            "project": "https://randomtutu.github.io/FinSearchComp/",
            "paper": "https://arxiv.org/abs/2509.13160",
            "github": "https://github.com/randomtutu/FinSearchComp",
        },
        "sources": [
            SourceRecord(
                "FinSearchComp project page",
                "https://randomtutu.github.io/FinSearchComp/",
                "project",
                "Project page for the open-domain financial search benchmark.",
            ),
            SourceRecord(
                "FinSearchComp paper",
                "https://arxiv.org/abs/2509.13160",
                "paper",
                "Paper abstract provides task families and dataset scale.",
            ),
        ],
        "reliability_notes": [
            "Good test case for search-specific and finance-specific capability tags.",
            "Some answers are time-sensitive, so result reproduction needs retrieval dates.",
        ],
        "confidence": 0.9,
    },
    {
        "name": "OneMillion-Bench",
        "slug": "onemillion-bench",
        "phase": "test",
        "status": "resolved",
        "aliases": ["$OneMillion-Bench", "$1M-Bench", "One Million Bench"],
        "organization": "OneMillion-Bench authors",
        "year": "2026",
        "domain": ["expert tasks", "professional domains", "agent reliability"],
        "evaluates": "Language agents on economically consequential expert-level tasks across law, finance, industry, healthcare, and natural science.",
        "task_format": "Long-horizon expert tasks requiring authoritative source retrieval, evidence reconciliation, domain rules, and constrained decisions.",
        "task_categories": ["law", "finance", "industry", "healthcare", "natural science"],
        "evaluation_method": "Rubric-based evaluation of factual accuracy, logical coherence, practical feasibility, and professional compliance.",
        "dataset_size": "400 expert-curated tasks.",
        "data_access": "Paper is public; code/data access should be confirmed from the project repository if available.",
        "artifacts": {
            "paper": "https://arxiv.org/abs/2603.07980",
        },
        "sources": [
            SourceRecord(
                "$OneMillion-Bench paper",
                "https://arxiv.org/abs/2603.07980",
                "paper",
                "Paper abstract describes domains, task count, and evaluation rubric.",
            )
        ],
        "reliability_notes": [
            "Search results collide with unrelated 'One Million' entities; exact aliases matter.",
            "Project/data repository should be verified in the next pipeline feature.",
        ],
        "confidence": 0.82,
    },
    {
        "name": "IBFE",
        "slug": "ibfe",
        "phase": "test",
        "status": "ambiguous",
        "aliases": [],
        "organization": "Unknown",
        "year": "",
        "domain": ["unknown"],
        "evaluates": "Unresolved acronym. The current pipeline cannot confidently map IBFE to a public LLM/agent benchmark.",
        "task_format": "Unknown until full name or source link is provided.",
        "task_categories": [],
        "evaluation_method": "Unknown.",
        "dataset_size": "Unknown.",
        "data_access": "Unknown.",
        "artifacts": {},
        "sources": [],
        "reliability_notes": [
            "IBFE is intentionally kept as a low-confidence test case for ambiguity handling.",
            "Ask for the full name or one source link before treating it as a resolved benchmark.",
        ],
        "confidence": 0.18,
    },
]
